diff_cont:
  ros__parameters:
    publish_rate: 30.0
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    left_wheel_names: ['base_left_wheel_joint']
    right_wheel_names: ['base_right_wheel_joint']
    wheel_separation: 0.45
    wheel_radius: 0.1
    use_stamped_vel: false