<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />
    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_length" value="0.3" />

    <xacro:macro name="arms" params="name x y z color">
        <link name="${name}_link">
            <visual>
                <geometry>
                    <cylinder radius="${arm_radius}" length="${arm_length}" />
                </geometry>
                <origin xyz="${x} ${y} ${z}" />
                <material name="${color}" />
            </visual>
        </link>
    </xacro:macro>
    
    <link name="base_footprint" />
    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="orange" />
        </visual>
    </link>
    <xacro:arms name="forearm" x="0" y="0" z="${arm_length / 2.0}" color="yellow" />
    <xacro:arms name="hand" x="0" y="0" z="${arm_length / 2.0}" color="orange" />

    <joint name="arm_base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="arm_base_link" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    <joint name="base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <axis xyz="0 1 0" />
        <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0"/>
        <limit lower="0" upper="${pi / 2.0}" effort="100" velocity="100" />
        <dynamic friction="0.3" damping="0.3" />
    </joint>
    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <axis xyz="0 1 0" />
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
        <limit lower="0" upper="${pi / 2.0}" effort="100" velocity="100" />
        <dynamic friction="0.3" damping="0.3" />
    </joint>


</robot>