<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_length" value="0.3" />

    <xacro:macro name="arms" params="name x y z color">
        <link name="${name}_link">
            <visual>
                <geometry>
                    <cylinder radius="${arm_radius}" length="${arm_length}" />
                </geometry>
                <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
                <material name="${color}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${arm_radius}" length="${arm_length}" />
                </geometry>
                <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="0.3" r="${arm_radius}" h="${arm_length}" 
                                    o_xyz="${x} ${y} ${z}" o_rpy="0 0 0" />
        </link>
    </xacro:macro>

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="0.5" x="${arm_base_length}" y="${arm_base_width}" z="${arm_base_height}"
                           o_xyz="0 0 ${arm_base_height/2.0}" o_rpy="0 0 0" />
    </link>

    <xacro:arms name="forearm" x="0" y="0" z="${arm_length / 2.0}" color="yellow" />
    <xacro:arms name="hand" x="0" y="0" z="${arm_length / 2.0}" color="orange" />

    <joint name="base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <axis xyz="0 1 0" />
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>
    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <axis xyz="0 1 0" />
        <origin xyz="0 0 ${arm_length}" rpy="0 0 0"/>
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.3" damping="0.3" />
    </joint>

    <xacro:include filename="arm_gazebo.xacro" />
</robot>