<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <link name="laser_link">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.05" />
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.05" />
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="0.05" h="0.05" o_xyz="0 0 0.025" o_rpy="0 0 0" />
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="base_link" />
        <child link="laser_link" />
        <origin xyz="${base_length / 4} 0 ${base_height}" rpy="0 0 0" />
    </joint>

     <gazebo reference="laser_link">
        <sensor name="lidar_sensor" type="gpu_lidar">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>2</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </lidar>
            <topic>scan</topic>
            <always_on>1</always_on>
            <gz_frame_id>laser_link</gz_frame_id>
        </sensor>
    </gazebo>

</robot>